### ISSUE TITLE
Move speaker test button on the Audio Bait page. 

### ISSUE THREAD

**Issue by clare** [TheCacophonyProject/management-interface#90]
The Speaker test button is under the Advanced>>Speaker Test page.   It would be much more useful if it was on the AudioBait page.   

1.   Move the speaker test to the top of the audiobait page. 
2.  If you want make it so you can also play the audiobait sounds to check the levels.

**Comment by Davo36** [comment]
I can do this Clare.  Where on that page do you think it should go?

**Comment by clare** [comment]
Thanks, That would be fab.   I am in the process of looking at the page in full (with an audio bait schedule on it).  When I get that working I'll get back to you.

**Comment by Davo36** [comment]
Clare, I was thinking about the audio bait page.  It would be good if users could play those sounds directly from that page.  Then they could listen to the sound to make sure it's what they want.  They could also hear the volume and make sure it's what they want.

Also, can all users edit their schedule via the existing browse-old... website?  It would actually be good if they could do it via the Management Interface I reckon.  So they can be standing right by the camera setting up the audio bait schedule as they wish it to be.  Fair bit more work in this of course.

One other small thing, which is kind of related, is that sometimes users may just want to turn off audiobait.  Like just stop it entirely for the forseeable future.  So a 'Stop Audio Bait' button might be useful.

**Comment by clare** [comment]
@Davo36  they are all fantastic ideas.   Can we start by 
1.  First moving the speaker test button to the top of the audiobait page.  Ie after the title.  
2.  Start by playing the sounds in the loaded audio bait.  (remember that one of the options is a random sound). 

We'll make a card for the other parts, but they need a bit more thought due to the way audiobait is set up.   For instance it is designed that many devices can share settings.  In that case do they all change?  And how are the changes communicated to the server?   Even stopping audio bait needs to be able to reflected in the server or it could be quite confusing.

**Comment by clare** [comment]
(I think it is still worth having the speaker test in case there is no audiobait sounds downloaded).

**Comment by Davo36** [comment]
Ok, I'll give it a whirl.
